openapi: 3.0.0
info:
  title: My Node API
  version: 1.0.0
  description: API mô tả bằng Swagger

servers:
  - url: http://localhost:3000

security:
  - bearerAuth: []

paths:
  /hello:
    get:
      summary: Trả về lời chào
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /login:
    post:
      summary: Đăng nhập người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "sv001"
                type:
                  type: string
                  enum: [lecturer, student]
                  example: "student"
                password:
                  type: string
                  example: "123456"
                forget:
                  type: integer
                  example: 0
      responses:
        "200":
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
        "401":
          description: Sai thông tin đăng nhập

  /signup:
    post:
      summary: Đăng ký tài khoản mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Nguyen Van A"
                email:
                  type: string
                  example: "a@student.edu"
                password:
                  type: string
                  example: "123456"
                type:
                  type: string
                  enum: [lecturer, student]
                  example: "student"
                id:
                  type: integer
                  example: 101
      responses:
        "201":
          description: Đăng ký thành công
        "400":
          description: Email đã tồn tại

  /changePassword:
    post:
      summary: Đổi mật khẩu
      security:
        - bearerAuth: [] # ⬅⬅⬅ Yêu cầu JWT token ở đây
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "sv001"
                oldPassword:
                  type: string
                  example: "123456"
                newPassword:
                  type: string
                  example: "654321"
                type:
                  type: string
                  enum: [lecturer, student]
                  example: "student"
      responses:
        "200":
          description: Đổi mật khẩu thành công
        "401":
          description: Mật khẩu cũ không đúng
        "404":
          description: Không tìm thấy người dùng

  /checkOTP:
    post:
      summary: Kiểm tra OTP đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "sv001"
                otp:
                  type: number
                  example: 123456
                type:
                  type: sring
                  example: "student"
                id: 
                  type: number
                  example: 123
      responses:
        "200":
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Sai thông tin đăng nhập

  /resetPassword:
    post:
      summary: Reset mật khẩu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "a@student.edu"
                newPassword:
                  type: string
                  example: "123456"
                type:
                  type: string
                  enum: [lecturer, student]
                  example: "student"
      responses:
        "201":
          description: Reset thành công
        "400":
          description: Email không tồn tại

  /rooms:
    get:
      summary: Lấy danh sách tất cả các phòng
      parameters:
        - name: building
          in: query
          schema:
            type: string
        - name: device
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Danh sách phòng
        "404":
          description: Ko có phòng nào
    post:
      summary: Tạo phòng mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                  example: "ROOM_B3_301"
                roomName:
                  type: string
                  example: "Room B3 301"
                building:
                  type: string
                  example: "B3"
                roomNumber:
                  type: number
                  example: 301
                capacity:
                  type: number
                  example: 70
                devices:
                  type: array
                  items:
                    type: string
                  example: ["light", "projector", "fan"]
                corridor_id:
                  type: string
                  example: "CORRIDOR_B3_3"
      responses:
        "201":
          description: Tạo phòng thành công
        "400":
          description: Lỗi tạo phòng

  /rooms/{id}:
    get:
      summary: Lấy chi tiết một phòng
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Thông tin chi tiết phòng
        "404":
          description: Không tìm thấy phòng

    /rooms/{id}:
    put:
      summary: Cập nhật thông tin phòng + lịch dạy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomName:
                  type: string
                  example: "Phòng B4 - sửa lần 3"
                roomNumber:
                  type: number
                  example: 403
                building:
                  type: string
                  example: "B4"
                capacity:
                  type: number
                  example: 90
                devices:
                  type: array
                  items:
                    type: string
                  example: ["light", "projector", "camera"]
                corridor_id:
                  type: string
                  example: "CORRIDOR_B4_2"
                scheduleUpdates:
                  type: array
                  items:
                    type: object
                    properties:
                      date:
                        type: string
                        format: date
                        example: "2025-05-01"
                      startPeriod:
                        type: number
                        example: 7
                      endPeriod:
                        type: number
                        example: 8
                      teacherId:
                        type: number
                        example: 3
                      lectureTitle:
                        type: string
                        example: "Toán rời rạc"
      responses:
        "200":
          description: Cập nhật thành công
        "400":
          description: Lỗi cập nhật phòng
        "404":
          description: Không tìm thấy phòng hoặc lịch

    delete:
      summary: Xoá phòng
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Xoá thành công
  /schedules:
    get:
      summary: Lấy tất cả lịch dạy (có thể lọc)
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date
          description: Lọc theo ngày đăng ký
        - name: usedDate
          in: query
          schema:
            type: string
            format: date
          description: Lọc theo ngày dạy
        - name: room_id
          in: query
          schema:
            type: string
          description: Lọc theo mã phòng
        - name: teacherId
          in: query
          schema:
            type: string
          description: Lọc theo ID giảng viên
      responses:
        "200":
          description: Trả về danh sách lịch dạy
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    room_id:
                      type: string
                    teacherId:
                      type: string
                    date:
                      type: string
                      format: date
                    startPeriod:
                      type: integer
                    endPeriod:
                      type: integer
                    lectureTitle:
                      type: string
        "500":
          description: Lỗi máy chủ

    post:
      summary: Tạo lịch học mới
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: string
                  example: "ROOM_B3_301"
                usedDate:
                  type: string
                  format: date
                  example: "2025-04-28"
                startPeriod:
                  type: integer
                  example: 3
                endPeriod:
                  type: integer
                  example: 5
                lectureTitle:
                  type: string
                  example: "Toán rời rạc"
                teacherId:
                  type: interger
                  example: 123456
      responses:
        "201":
          description: Tạo lịch học thành công
        "400":
          description: Lịch học bị trùng
        "500":
          description: Lỗi server

  /schedules/{id}:
    get:
      summary: Lấy thông tin chi tiết của một lịch học
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID của lịch học
      responses:
        "200":
          description: Trả về thông tin lịch học
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  room_id:
                    type: string
                  teacherId:
                    type: string
                  date:
                    type: string
                    format: date
                  usedDate:
                    type: string
                    format: date
                  startPeriod:
                    type: integer
                  endPeriod:
                    type: integer
                  lectureTitle:
                    type: string
        "404":
          description: Không tìm thấy lịch học
        "500":
          description: Lỗi server

    put:
      summary: Cập nhật lịch học
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: string
                  example: "ROOM_B3_301"
                date:
                  type: string
                  format: date
                  example: "2025-05-01"
                usedDate:
                  type: string
                  format: date
                  example: "2025-04-28"
                startPeriod:
                  type: integer
                  example: 3
                endPeriod:
                  type: integer
                  example: 5
                lectureTitle:
                  type: string
                  example: "Toán rời rạc"
      responses:
        "200":
          description: Cập nhật thành công
        "403":
          description: Không được phép chỉnh sửa lịch này
        "404":
          description: Không tìm thấy lịch
        "500":
          description: Lỗi server

    delete:
      summary: Xoá lịch học
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Xoá thành công
        "403":
          description: Không được phép xoá lịch này
        "404":
          description: Không tìm thấy lịch
        "500":
          description: Lỗi server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
